Update git hooks to latest tool versions

diff --git a/etc/git-hooks/pre-commit-clang-format-hook b/etc/git-hooks/pre-commit-clang-format-hook
--- a/etc/git-hooks/pre-commit-clang-format-hook
+++ b/etc/git-hooks/pre-commit-clang-format-hook
@@ -7,8 +7,14 @@
 
 ##################################################################
 # SETTINGS
+# set file containing the clang-format version number:
+VERSIONFILE="CMakeLists.txt"
+
+# retrieve the version number from the VERSIONFILE
+CLANG_FORMAT_VERSION=$(git cat-file blob master:"$VERSIONFILE" | grep -m 1 'CLANG_FORMAT_VERSION' | sed 's/^[^"]*"//;s/"[^"]*$//')
+
 # set path to clang-format binary
-for bin in "clang-format-8" "clang-format";
+for bin in "clang-format-$CLANG_FORMAT_VERSION" "clang-format";
 do
     CLANG_FORMAT=$(which "$bin")
     [ -n "$CLANG_FORMAT" ] && break
@@ -60,13 +66,13 @@ if [ ! -x "$CLANG_FORMAT" ] ; then
     exit 1
 fi
 
-if ! "$CLANG_FORMAT" --version | grep 'clang-format version 8\.0' >/dev/null 2>/dev/null; then
+if ! "$CLANG_FORMAT" --version | grep "clang-format version $CLANG_FORMAT_VERSION" >/dev/null 2>/dev/null; then
     # Be indulgent with OSX users, no 4.0 seems to be available...
-    if [[ "$OSTYPE" != "darwin"* ]]; then
-        printf "Error: clang-format version 8.0 is required (exactly), cannot check format!\n"
+    if [ "$OSTYPE" != "darwin"* ]; then
+        printf "Error: clang-format version $CLANG_FORMAT_VERSION is required (exactly), cannot check format!\n"
         exit 1
     else
-        printf "Warning: clang-format version 8.0 is required, formatting might be incompatible!\n"
+        printf "Warning: clang-format version $CLANG_FORMAT_VERSION is required, formatting might be incompatible!\n"
     fi
 fi
 
